### ISSUE TITLE
importerror: util

### ISSUE THREAD

**Issue by tacoe** [mitsuhiko/pluginbase#9] opened 2015-10-21 20:09 UTC
when I have:

```
from pluginbase import PluginBase
from pyechonest import config
from pyechonest import song
```

I get 

```
Traceback (most recent call last):
  File "partyled.py", line 9, in <module>
    from pyechonest import song
  File "/usr/local/lib/python2.7/site-packages/pluginbase.py", line 404, in plugin_import
    fromlist, level)
  File "build/bdist.macosx-10.10-x86_64/egg/pyechonest/song.py", line 12, in <module>
  File "/usr/local/lib/python2.7/site-packages/pluginbase.py", line 404, in plugin_import
    fromlist, level)
ImportError: No module named util
```

however if I change the order to

```
from pyechonest import config
from pyechonest import song
from pluginbase import PluginBase
```

things work fine. Given the order in which things override, I'm inclined to suspect of PluginBase of doing something weird here.

**Comment by phretor** [comment] 2015-11-19 22:22
This seems related to #10 (if not the same)

**Comment by zeroSteiner** [comment] 2016-06-17 01:56
I was able to reproduce this with `pyechonest==9.0.0` / `pluginbase==0.3` and have confirmed that it (like #10) is also a duplicate of #5 which has been fixed and closed.

**Closed by zeroSteiner** 2016-06-17 01:56 UTC
Labels: bug, duplicate
