### ISSUE TITLE
DeprecationWarning in pluginbase.py line 439

### ISSUE THREAD

**Issue by awlosnie** [mitsuhiko/pluginbase#20] opened 2020-08-31 15:15 UTC
c:\python\python37\lib\site-packages\pluginbase.py:439: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

**Comment by zeroSteiner** [comment] 2020-09-10 22:57
Can you please provide some additional details as to how I can reproduce this warning? It appears to be warning about the old `imp` module being used, but I can't find any reference to it in `pluginbase.py`. I ran through the test cases and did not get this warning. I also checked that the `builtins.__import__` function that's used by 3.7 is not backed by the `imp` module. I checked this because that looks like what's called on L439 for a Python3.7 installation. That is to say that when I can run the following without getting the deprecation warning, I even tried on Windows.

```
>>> import builtins
>>> builtins.__import__
<built-in function __import__>
>>> builtins.__import__('os')
<module 'os' from '/usr/lib64/python3.8/os.py'>
>>> 
```

**Comment by zeroSteiner** [comment] 2020-10-14 15:07
I'm going to close this out. I can't reproduce it. If you get back around to it and can provide some steps, I'd be happy to take a closer look and address the issue.

Thanks!

**Closed by zeroSteiner** 2020-10-14 15:07 UTC
Labels: bug, invalid
